version: "3.9"

x-freqai-settings: &freqai-settings
  image: freqtradeorg/freqtrade:stable_freqai
  restart: unless-stopped
  volumes:
    - "./user_data:/freqtrade/user_data"
    - "./user_data/data:/freqtrade/user_data/data"
    - "./configs:/freqtrade/configs"
    - "./${FREQTRADE__STRATEGY:-NostalgiaForInfinityX7}.py:/freqtrade/${FREQTRADE__STRATEGY:-NostalgiaForInfinityX7}.py"
    - "./user_data/freqaimodels:/freqtrade/user_data/freqaimodels"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}"]
    interval: 1m30s
    timeout: 10s
    retries: 3
    start_period: 40s
    start_interval: 5s
  env_file:
    - path: .env
      required: false

services:
  freqtrade-freqai:
    <<: *freqai-settings
    container_name: ${FREQTRADE__BOT_NAME:-Example_Test_Account}_freqai_${FREQTRADE__EXCHANGE__NAME:-binance}_${FREQTRADE__TRADING_MODE:-futures}
    ports:
      - "${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}:${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}"
    command: >
      trade
      --config ${FREQAI_CONFIG:-configs/freqai-config.example.json}
      --db-url sqlite:////freqtrade/user_data/${FREQTRADE__BOT_NAME:-Example_Test_Account}_${FREQTRADE__EXCHANGE__NAME:-binance}_${FREQTRADE__TRADING_MODE:-futures}-freqai-tradesv3.sqlite
      --log-file user_data/logs/${FREQTRADE__BOT_NAME:-Example_Test_Account}-${FREQTRADE__EXCHANGE__NAME:-binance}-freqai-${FREQTRADE__TRADING_MODE:-futures}.log
      --strategy-path .
      --freqaimodels-path /freqtrade/user_data/freqaimodels
      --freqai
